# Naziv aplikacije
spring.application.name=TehnoZonaSpring

# Putanja do JSON fajla (ako koristiš statički fajl unutar JAR-a)
app.data.products-file=classpath:static/data/products.json

# Konfiguracija baze (dinamički kroz ENV varijable)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA podešavanja
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
